export default {
  state: {
    allCategoriesList: [
      {
        id: "1",
        tag: "bedroom",
        src: require("@/assets/images/projects_img1.png"),
        alt: "bedroom one",
        title: "Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "2",
        tag: "bedroom",
        src: require("@/assets/images/projects_img2.png"),
        alt: "bedroom two",
        title: "Classic Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "3",
        tag: "bedroom",
        src: require("@/assets/images/projects_img3.png"),
        alt: "bedroom three",
        title: "Minimal Bedroom Table",
        subject: "Decor / Artchitecture",
      },
      {
        id: "4",
        tag: "bedroom",
        src: require("@/assets/images/projects_img4.png"),
        alt: "bedroom four",
        title: "Modern Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "5",
        tag: "bedroom",
        src: require("@/assets/images/projects_img5.png"),
        alt: "bedroom five",
        title: "Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "6",
        tag: "bedroom",
        src: require("@/assets/images/projects_img6.png"),
        alt: "bedroom six",
        title: "Modern Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "7",
        tag: "bedroom",
        src: require("@/assets/images/projects_img7.png"),
        alt: "bedroom seven",
        title: "System Bedroom Table",
        subject: "Decor / Artchitecture",
      },
      {
        id: "8",
        tag: "bedroom",
        src: require("@/assets/images/projects_img8.png"),
        alt: "bedroom eight",
        title: "Modern Bedroom",
        subject: "Decor / Artchitecture",
      },

      {
        id: "9",
        tag: "bedroom",
        src: require("@/assets/images/projects_img1.png"),
        alt: "bedroom nine",
        title: "Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "10",
        tag: "bedroom",
        src: require("@/assets/images/projects_img2.png"),
        alt: "bedroom ten",
        title: "Classic Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "11",
        tag: "bedroom",
        src: require("@/assets/images/projects_img1.png"),
        alt: "bedroom eleven",
        title: "Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "12",
        tag: "bedroom",
        src: require("@/assets/images/projects_img2.png"),
        alt: "bedroom twelve",
        title: "Classic Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "13",
        tag: "bedroom",
        src: require("@/assets/images/projects_img2.png"),
        alt: "bedroom thirteen",
        title: "Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "14",
        tag: "bedroom",
        src: require("@/assets/images/projects_img1.png"),
        alt: "bedroom fourteen",
        title: "Classic Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "15",
        tag: "bedroom",
        src: require("@/assets/images/projects_img2.png"),
        alt: "bedroom fifteen",
        title: "Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "16",
        tag: "bedroom",
        src: require("@/assets/images/projects_img1.png"),
        alt: "bedroom sixteen",
        title: "Classic Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },

      {
        id: "17",
        tag: "bedroom",
        src: require("@/assets/images/projects_img3.png"),
        alt: "bedroom seventeen",
        title: "Minimal Bedroom Table",
        subject: "Decor / Artchitecture",
      },
      {
        id: "18",
        tag: "bedroom",
        src: require("@/assets/images/projects_img4.png"),
        alt: "bedroom eighteen",
        title: "Modern Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "19",
        tag: "bedroom",
        src: require("@/assets/images/projects_img3.png"),
        alt: "bedroom nineteen",
        title: "Minimal Bedroom Table",
        subject: "Decor / Artchitecture",
      },
      {
        id: "20",
        tag: "bedroom",
        src: require("@/assets/images/projects_img4.png"),
        alt: "bedroom twenty",
        title: "Modern Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "21",
        tag: "bedroom",
        src: require("@/assets/images/projects_img4.png"),
        alt: "bedroom twenty-one",
        title: "Minimal Bedroom Table",
        subject: "Decor / Artchitecture",
      },
      {
        id: "22",
        tag: "bedroom",
        src: require("@/assets/images/projects_img3.png"),
        alt: "bedroom twenty-two",
        title: "Modern Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "23",
        tag: "bedroom",
        src: require("@/assets/images/projects_img4.png"),
        alt: "bedroom twehty-three",
        title: "Minimal Bedroom Table",
        subject: "Decor / Artchitecture",
      },
      {
        id: "24",
        tag: "bedroom",
        src: require("@/assets/images/projects_img3.png"),
        alt: "bedroom twenty-four",
        title: "Modern Bedroom",
        subject: "Decor / Artchitecture",
      },

      {
        id: "25",
        tag: "bedroom",
        src: require("@/assets/images/projects_img6.png"),
        alt: "bedroom twenty-five",
        title: "Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "26",
        tag: "bedroom",
        src: require("@/assets/images/projects_img5.png"),
        alt: "bedroom twenty-six",
        title: "Modern Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "27",
        tag: "bedroom",
        src: require("@/assets/images/projects_img6.png"),
        alt: "bedroom twenty-seven",
        title: "Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "28",
        tag: "bedroom",
        src: require("@/assets/images/projects_img5.png"),
        alt: "bedroom twenty-eight",
        title: "Modern Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "29",
        tag: "bedroom",
        src: require("@/assets/images/projects_img5.png"),
        alt: "bedroom twenty-nine",
        title: "Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "30",
        tag: "bedroom",
        src: require("@/assets/images/projects_img6.png"),
        alt: "bedroom thirty",
        title: "Modern Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "31",
        tag: "bedroom",
        src: require("@/assets/images/projects_img5.png"),
        alt: "bedroom thirty-one",
        title: "Minimal Bedroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "32",
        tag: "bedroom",
        src: require("@/assets/images/projects_img6.png"),
        alt: "bedroom thirty-two",
        title: "Modern Bedroom",
        subject: "Decor / Artchitecture",
      },

      {
        id: "33",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom1.png"),
        alt: "bathroom one",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "34",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom2.png"),
        alt: "bathroom two",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "35",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom3.png"),
        alt: "bathroom three",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "36",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom4.png"),
        alt: "bathroom four",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "37",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom5.png"),
        alt: "bathroom five",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "38",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom6.png"),
        alt: "bathroom six",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "39",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom7.png"),
        alt: "bathroom seven",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "40",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom8.png"),
        alt: "bathroom eight",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },

      {
        id: "41",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom1.png"),
        alt: "bathroom nine",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "42",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom2.png"),
        alt: "bathroom ten",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "43",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom1.png"),
        alt: "bathroom eleven",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "44",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom2.png"),
        alt: "bathroom twelve",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "45",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom2.png"),
        alt: "bathroom thirteen",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "46",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom1.png"),
        alt: "bathroom fourteen",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "47",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom2.png"),
        alt: "bathroom fifteen",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "48",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom1.png"),
        alt: "bathroom sixteen",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },

      {
        id: "49",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom3.png"),
        alt: "bathroom seventeen",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "50",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom4.png"),
        alt: "bathroom eighteen",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "51",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom3.png"),
        alt: "bathroom nineteen",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "52",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom4.png"),
        alt: "bathroom twenty",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "53",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom4.png"),
        alt: "bathroom twenty-one",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "54",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom3.png"),
        alt: "bathroom twenty-two",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "55",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom4.png"),
        alt: "bathroom twenty-three",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "56",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom3.png"),
        alt: "bathroom twenty-four",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },

      {
        id: "57",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom6.png"),
        alt: "bathroom twenty-five",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "58",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom5.png"),
        alt: "bathroom twenty-six",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "59",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom6.png"),
        alt: "bathroom twenty-seven",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "60",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom5.png"),
        alt: "bathroom twenty-eight",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "61",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom5.png"),
        alt: "bathroom twenty-nine",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "62",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom6.png"),
        alt: "bathroom thirty",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "63",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom5.png"),
        alt: "bathroom thirty-one",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "64",
        tag: "bathroom",
        src: require("@/assets/images/projects_bathroom6.png"),
        alt: "bathroom thirty-two",
        title: "Modern Bathroom",
        subject: "Decor / Artchitecture",
      },

      {
        id: "65",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen1.png"),
        alt: "kitchen one",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "66",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen2.png"),
        alt: "kitchen two",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "67",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen3.png"),
        alt: "kitchen three",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "68",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen4.png"),
        alt: "kitchen four",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "69",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen5.png"),
        alt: "kitchen five",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "70",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen6.png"),
        alt: "kitchen six",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "71",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen7.png"),
        alt: "kitchen seven",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "72",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen8.png"),
        alt: "kitchen eight",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },

      {
        id: "73",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen1.png"),
        alt: "kitchen nine",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "74",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen2.png"),
        alt: "kitchen ten",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "75",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen1.png"),
        alt: "kitchen eleven",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "76",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen2.png"),
        alt: "kitchen twelve",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "77",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen2.png"),
        alt: "kitchen thirteen",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "78",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen1.png"),
        alt: "kitchen fourteen",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "79",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen2.png"),
        alt: "kitchen fifteen",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "80",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen1.png"),
        alt: "kitchen sixteen",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },

      {
        id: "81",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen3.png"),
        alt: "kitchen seventeen",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "82",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen4.png"),
        alt: "kitchen eighteen",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "83",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen3.png"),
        alt: "kitchen nineteen",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "84",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen4.png"),
        alt: "kitchen twenty",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "85",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen4.png"),
        alt: "kitchen twenty-one",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "86",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen3.png"),
        alt: "kitchen twenty-two",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "87",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen4.png"),
        alt: "kitchen twenty-three",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "88",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen3.png"),
        alt: "kitchen twenty-four",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },

      {
        id: "89",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen6.png"),
        alt: "kitchen twenty-five",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "90",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen5.png"),
        alt: "kitchen twenty-six",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "91",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen6.png"),
        alt: "kitchen twenty-seven",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "92",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen5.png"),
        alt: "kitchen twenty-eight",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "93",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen5.png"),
        alt: "kitchen twenty-nine",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "94",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen6.png"),
        alt: "kitchen thirty",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "95",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen5.png"),
        alt: "kitchen thirty-one",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },
      {
        id: "96",
        tag: "kitchen",
        src: require("@/assets/images/projects_kitchen6.png"),
        alt: "kitchen thirty-two",
        title: "Modern Kitchen",
        subject: "Decor / Artchitecture",
      },

      {
        id: "97",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom1.png"),
        alt: "livingroom one",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "98",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom2.png"),
        alt: "livingroom two",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "99",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom3.png"),
        alt: "livingroom three",
        title: "Modern Livingroom 3",
        subject: "Decor / Artchitecture",
      },
      {
        id: "100",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom4.png"),
        alt: "livingroom four",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "101",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom5.png"),
        alt: "livingroom five",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "102",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom6.png"),
        alt: "livingroom six",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "103",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom7.png"),
        alt: "livingroom seven",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "104",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom8.png"),
        alt: "livingroom eight",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },

      {
        id: "105",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom1.png"),
        alt: "livingroom nine",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "106",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom2.png"),
        alt: "livingroom ten",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "107",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom1.png"),
        alt: "livingroom eleven",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "108",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom2.png"),
        alt: "livingroom twelve",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "109",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom2.png"),
        alt: "livingroom thirteen",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "110",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom1.png"),
        alt: "livingroom fourteen",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "111",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom2.png"),
        alt: "livingroom fifteen",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "112",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom1.png"),
        alt: "livingroom sixteen",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },

      {
        id: "113",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom3.png"),
        alt: "livingroom seventeen",
        title: "Modern Livingroom 3",
        subject: "Decor / Artchitecture",
      },
      {
        id: "114",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom4.png"),
        alt: "livingroom eighteen",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "115",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom3.png"),
        alt: "livingroom nineteen",
        title: "Modern Livingroom 3",
        subject: "Decor / Artchitecture",
      },
      {
        id: "116",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom4.png"),
        alt: "livingroom twenty",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "117",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom4.png"),
        alt: "livingroom twenty-one",
        title: "Modern Livingroom 3",
        subject: "Decor / Artchitecture",
      },
      {
        id: "118",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom3.png"),
        alt: "livingroom twenty-two",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "119",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom4.png"),
        alt: "livingroom twenty-three",
        title: "Modern Livingroom 3",
        subject: "Decor / Artchitecture",
      },
      {
        id: "120",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom3.png"),
        alt: "livingroom twenty-four",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },

      {
        id: "121",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom6.png"),
        alt: "livingroom twenty-five",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "122",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom5.png"),
        alt: "livingroom twenty-six",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "123",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom6.png"),
        alt: "livingroom twenty-seven",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "124",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom5.png"),
        alt: "livingroom twenty-eight",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "125",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom5.png"),
        alt: "livingroom twenty-nine",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "126",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom6.png"),
        alt: "livingroom thirty",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "127",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom5.png"),
        alt: "livingroom thirty-one",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
      {
        id: "128",
        tag: "livingroom",
        src: require("@/assets/images/projects_livingroom6.png"),
        alt: "livingroom thirty-two",
        title: "Modern Livingroom",
        subject: "Decor / Artchitecture",
      },
    ],
  },
  getters: {
    getAllCategoriesList(state) {
      return state.allCategoriesList;
    },
  },
};
